config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions do
    resources :answers, only: %i[create destroy update edit]
  end

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: %i[create]

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = 'Answer created successfully'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(5)
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer deleted successfully'
    redirect_to question_path(@question)
  end

  def edit; end

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated successfully'
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      render :edit
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small>
        <time datetime="<%= answer.formatted_created_at %>">
          <%= answer.formatted_created_at %>
        </time>
      </small>
      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    <%= link_to "Edit", edit_question_answer_path(question, answer), class: "btn btn-secondary" %>
    <%= link_to "Delete",
                  question_answer_path(question, answer),
                  class: "btn btn-danger",
                  data: { method: :delete, confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render "shared/errors", object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :body, placeholder: "Body", class: "form-control" %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: "btn btn-primary" %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, "Edin Answer" %>
<% currently_at "Answer" %>

<div class="d-flex justify-content-between mb-4">
  <h1>Edit answer</h1>
  <%= link_to "<- Back", :back, class: "btn" %>
</div>

<%= render "form" %>